export const menuItems = [
  {
    id: 1,
    name: "Masala Dosa",
    price: 2.5,
    priceDisplay: "$2.50",
    category: "Food",
    description: "Crispy dosa filled with spicy mashed potatoes.",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG05O5NcCE_kSlfxvXQm7tppLU1n4xF3ryyA&s",
    inStock: true,
  },
  {
    id: 2,
    name: "Pav Bhaji",
    price: 2.0,
    priceDisplay: "$2.00",
    category: "Food",
    description: "Spicy mashed vegetables served with buttered bread.",
    image: "https://source.unsplash.com/400x300/?pavbhaji",
    inStock: false,
  },
  {
    id: 3,
    name: "Chole Bhature",
    price: 3.0,
    priceDisplay: "$3.00",
    category: "Food",
    description: "Fried bread with chickpea curry.",
    image: "https://source.unsplash.com/400x300/?cholebhature",
    inStock: true,
  },
  {
    id: 4,
    name: "Lassi",
    price: 1.2,
    priceDisplay: "$1.20",
    category: "Drinks",
    description: "Refreshing yogurt-based drink, sweet or salty.",
    image: "https://source.unsplash.com/400x300/?lassi",
    inStock: true,
  },
  // New unique items
  {
    id: 9,
    name: "Paneer Tikka",
    price: 4.0,
    priceDisplay: "$4.00",
    category: "Food",
    description: "Grilled paneer cubes marinated in spices and yogurt.",
    image: "https://source.unsplash.com/400x300/?paneer,tikka",
    inStock: true,
  },
  {
    id: 10,
    name: "Butter Chicken",
    price: 5.5,
    priceDisplay: "$5.50",
    category: "Food",
    description: "Tender chicken cooked in creamy tomato gravy.",
    image: "https://source.unsplash.com/400x300/?butter,chicken",
    inStock: true,
  },
  {
    id: 11,
    name: "Masala Chai",
    price: 1.0,
    priceDisplay: "$1.00",
    category: "Drinks",
    description: "Traditional Indian spiced tea made with milk and tea leaves.",
    image: "https://source.unsplash.com/400x300/?masalachai",
    inStock: true,
  },
  {
    id: 12,
    name: "Gulab Jamun",
    price: 2.0,
    priceDisplay: "$2.00",
    category: "Dessert",
    description: "Soft deep-fried dough balls soaked in rose-flavored sugar syrup.",
    image: "https://source.unsplash.com/400x300/?gulabjamun",
    inStock: true,
  },
  {
    id: 13,
    name: "Aloo Paratha",
    price: 2.5,
    priceDisplay: "$2.50",
    category: "Food",
    description: "Whole wheat flatbread stuffed with spiced mashed potatoes.",
    image: "https://source.unsplash.com/400x300/?alooparatha",
    inStock: true,
  },
];